accounts:
    # .damai.cn中的cookie完整字符串
    - cookie: ""
      remark: 账号1
      # 抢票轮训间隔, 单位毫秒
      interval: 30

      # 最早提前多少毫秒发包。 开抢剩余时间戳 = 开始售票的时间戳 - 当前时间戳。 当开抢剩余时间戳时间小于 submit_time时, 开始发送数据包。
      earliest_submit_time: 15

      ticket:
        # 需要抢购的门票ID, 门票详情页URL中的itemId.如:https://m.damai.cn/damai/detail/item.html?utm=&itemId=710947802955
        id: "719540964775"
        # 需要抢购的门票数量
        num: 1
        # 需要抢购的场次序号.
        sessions: 1
        # 需要抢购的票档序号
        grade: 3



